### ISSUE TITLE
Data Iterator Issue with Containing feature

### ISSUE THREAD

**Issue by vijaybalagopala** [org-scn-design-studio-community/lumiradesignercommunityext_src#2]
Hi,

 I wrote this code in the script that used to work for Design Studio but now isn't working with Lumira 2.0. Is there something new that I missed?

var rows_1 = DATAITERATOR_CTOS_TABLE.getRows().containing({"dimensions" : [{ "key":"ZLOC_NAME__ZGR_ORD", "value": "1"}]});

**Comment by entmike** [comment]
Probably a scope bug in 2.0 and fixable. Can you attach an error log?

**Comment by entmike** [comment]
Also be sure you are using the new Lumira Designer 2.0 extensions.

**Comment by vijaybalagopala** [comment]
Hi Mike,

            Yes, I'm using the Lumira 2.0 extensions. I have attached the error log from the Designer. Please let me know if you need anything else from my end. 
[Error Log Data Iterator.txt](https://github.com/org-scn-design-studio-community/lumiradesignercommunityext_src/files/1351029/Error.Log.Data.Iterator.txt)

**Comment by vijaybalagopala** [comment]
[Error Log Data Iterator.txt](https://github.com/org-scn-design-studio-community/lumiradesignercommunityext_src/files/1351095/Error.Log.Data.Iterator.txt)

**Comment by vijaybalagopala** [comment]
Hi Mike,

        Did you have a chance to take a look at this?

**Comment by entmike** [comment]
Vijay,

I looked at the code at it looks like this should work just fine.  It looks like I fixed this back on Aug 18th:

https://github.com/org-scn-design-studio-community/lumiradesignercommunityext_src/commit/33cb9cc07081b1a90e08273cb3d9383ebf97a70f#diff-1d076083521e140a61e930da74484735L3882

Can you confirm you are using the LATEST download (and downloaded after Aug 18) from here?

https://github.com/org-scn-design-studio-community/lumiradesignercommunityext/blob/master/releases/org.scn.community.sdk.extensions.zip?raw=true

**Comment by vijaybalagopala** [comment]
Hi Mike,

        yes I downloaded the file for Lumira 2.0 on Sep 26th. Post-installation we started having issues with that particular line.

**Comment by entmike** [comment]
That is strange.  Is it possible to create a small sample app and attach it for me to debug then?  This should be working just fine.  (Similar bug reported here: https://github.com/org-scn-design-studio-community/lumiradesignercommunityext/issues/8)

**Comment by vijaybalagopala** [comment]
var rows = DATAITERATOR_CTOS_TABLE.getRows();

var rows_1 = rows.containing({"dimensions" : [{ "key":"ZLOC_NAME__ZGR_ORD", "value": "01"}]});

This is all I have written.. And it fails at line 2.

**Comment by entmike** [comment]
My apologies, I think I found the error.  Related to scope...  Can you re-download and try again now?  I've just pushed a fix.

**Comment by vijaybalagopala** [comment]
Can I use the same link you have provided before in the conversation to download?

**Comment by entmike** [comment]
Yes, the download link will always be the same.

**Comment by vijaybalagopala** [comment]
OK. I'm trying now. Will let you know in a few minutes if it's fixed.

**Comment by vijaybalagopala** [comment]
Mike, it's working now ! Man am I happy or what ! Thank you for your quick help in resolving this for me.

**Comment by entmike** [comment]
Glad I could help!  Sorry for occasional delays in response, since it's a spare-time project, etc.  Good luck!

**Comment by entmike** [comment]
Closing this issue as it was resolved.
