### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by JonasDuclos** [org-scn-design-studio-community/lumiradesignercommunityext_src#3]
Hello dear community !

We are currently facing an issue with several of our Design Studio Application. Randomly, (but often after emptying the browser cache), we have a error message "Javascript error" (in local mode or in BIP mode).

We are in Design Studio 1.6 SP05 (and we won't go any further for now) and we are using SDK Community (last update).

Here the error message which can have thanks to our browser log (no log in Design Studio) :

![2018-02-26](https://user-images.githubusercontent.com/20657788/36666275-61b51d78-1aea-11e8-8d11-c612074af647.png)

Maybe you already met this error in your development and you will have an idea. We can't be sure this error is linked to SDK or standard because error is random, and it will be very complicated to have a similar application to reproduce the issue (because we don't know the origin and we have application with this issue and other without it (but both applications are built in the same way...)

Thank for your help ! 

Jonas.

**Comment by MartinPankraz** [comment]
Hi Jonas,

I don't see any reference to any of our components on your error log. Apart from that this github repsoitory targets the Lumira Designer 2.x release and not design studio. We keep the DesignStudio stuff in the old [place:](https://github.com/org-scn-design-studio-community/sdkpackage) . You can still download it from the option DesignStudio 1.6 [here](https://github.com/org-scn-design-studio-community/lumiradesignercommunityext).

Kind regards
Martin
